siteTitle="Veritone"
baseColor = "#4caf50"
bg = "#ffffff"
linkPrefix = "/veritone-docs"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/authentication/",
  "/docs/tutorials/",
  "/docs/tutorials/engines/",
  "/docs/tutorials/applications/",
  "/docs/api/",
  "/docs/api/recording/",
  "/docs/api/asset/",
  "/docs/api/job/",
  "/docs/api/search/",
  "/docs/faq/"
]